deployment:
  tasks:
    # 1. Define deploy path
    - export DEPLOYPATH=/home/samanva1/public_html/

    # 2. Copy files (excluding storage, vendor, node_modules, git files)
    - /bin/rsync -av --delete --exclude=".git" --exclude="vendor" --exclude="node_modules" ./ $DEPLOYPATH

    # 3. Navigate to deploy path
    - cd $DEPLOYPATH

    # 4. Install PHP dependencies (if composer is available in hosting)
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader

    # 5. Run Laravel optimizations
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
